# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # use `pre-commit autoupdate` to get the latest rev
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
#-   repo: https://github.com/pre-commit/mirrors-csslint
#    rev: v1.0.5  # use `pre-commit autoupdate` to get the latest rev
#    hooks:
#    -   id: csslint
#-   repo: https://github.com/thibaudcolas/curlylint
#    rev: v0.13.1  # use `pre-commit autoupdate` to get the latest rev
#    hooks:
#    -   id: curlylint
#-   repo: https://github.com/klieret/jekyll-relative-url-check
#    rev: v2.0.1  # use `pre-commit autoupdate` to get the latest rev
#    hooks:
#    -   id: jekyll-relative-url-check-html
#    -   id: jekyll-relative-url-check-markdown
#-   repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v2.7.1
#    hooks:
#    -   id: prettier
